version: '3.2'
services:

  # Form PA
  form-pa:
    container_name: form-pa
    image: italia/form-pa
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
